---
- name: Install apt key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: EA312927
    state: present
  tags: install

- name: Add mongod repository
  apt_repository:
    repo: deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse
    state: present
    filename: mongod
  tags: install

- name: Install mongod
  apt:
    state: present
    name: mongodb-org
    update_cache: yes
  tags: install

- name: Enable mongod unit
  systemd:
    name: mongod
    enabled: yes
  tags: install

- name: start mongod unit
  systemd:
    name: mongod
    state: started
  tags: install
