- name: Configure app  
  hosts: app
  gather_facts: false
  become: true
  tasks:
    - name: Add unit file for Puma
      copy:
        src: files/puma.service
        dest: /etc/systemd/system/puma.service
    
    - name: enable puma
      systemd: name=puma enabled=yes

    - name: Add config for DB connection
      template:
        src: templates/db_config.j2
        dest: /home/gcp_appUser/db_config
        owner: gcp_appUser
        group: gcp_appUser
      notify: reload puma


  handlers:
  - name: reload puma
    systemd: name=puma state=restarted
